from starkcore.utils.resource import Resource


class Signer(Resource):
    """# creditnote.Signer object
    Every time an CreditNote entity is updated, a corresponding creditnote.Signer
    is generated for the entity. This log is never generated by the
    user, but it can be retrieved to check additional information
    on the CreditNote.
    ## Parameters (required):
    - name [string]: signer name. ex: "Tony Stark"
    - contact [string]: email for the contract. ex: "tony@starkindustries.com"
    - method [string]: delivery method for the contract. ex: "link"
    ## Attributes (return-only):
    - id [string]: unique id returned when the Signer is created. ex: "5656565656565656"
    """

    def __init__(self, name, contact, method, id=None):
        Resource.__init__(self, id=id)

        self.name = name
        self.contact = contact
        self.method = method


_resource = {"class": Signer, "name": "Signer"}
