from ...utils import rest
from starkcore.utils.resource import Resource
from starkcore.utils.checks import check_datetime, check_date
from starkcore.utils.api import from_api_json
from ..__individualaccountattachment import _resource as _individual_account_attachment_resource


class Log(Resource):
    """# individualaccountattachment.Log object
    Every time an IndividualAccountAttachment entity is updated, a corresponding individualaccountattachment.Log
    is generated for the entity. This log is never generated by the
    user, but it can be retrieved to check additional information
    on the IndividualAccountAttachment.
    ## Attributes (return-only):
    - id [string]: unique id returned when the log is created. ex: "5656565656565656"
    - attachment [IndividualAccountAttachment]: IndividualAccountAttachment entity to which the log refers to.
    - errors [list of strings]: list of errors linked to this IndividualAccountAttachment event
    - type [string]: type of the IndividualAccountAttachment event which triggered the log creation. ex: "created", "success", "failed" or "deleted"
    - created [datetime.datetime]: creation datetime for the log. ex: datetime.datetime(2020, 3, 10, 10, 30, 0, 0)
    """

    def __init__(self, id, created, type, errors, attachment):
        Resource.__init__(self, id=id)

        self.created = check_datetime(created)
        self.type = type
        self.errors = errors
        self.attachment = from_api_json(_individual_account_attachment_resource, attachment)


_resource = {"class": Log, "name": "IndividualAccountAttachmentLog"}


def get(id, user=None):
    """# Retrieve a specific individualaccountattachment.Log
    Receive a single individualaccountattachment.Log object previously created by the Stark Infra API by its id
    ## Parameters (required):
    - id [string]: object unique id. ex: "5656565656565656"
    ## Parameters (optional):
    - user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call.
    ## Return:
    - individualaccountattachment.Log object with updated attributes
    """
    return rest.get_id(resource=_resource, id=id, user=user)


def query(limit=None, after=None, before=None, types=None, attachment_ids=None, user=None):
    """# Retrieve individualaccountattachment.Logs
    Receive a generator of individualaccountattachment.Log objects previously created in the Stark Infra API
    ## Parameters (optional):
    - limit [integer, default None]: maximum number of objects to be retrieved. Unlimited if None. ex: 35
    - after [datetime.date or string, default None]: date filter for objects created only after specified date. ex: datetime.date(2020, 3, 10)
    - before [datetime.date or string, default None]: date filter for objects created only before specified date. ex: datetime.date(2020, 3, 10)
    - types [list of strings, default None]: filter for log event types. ex: ["created", "success", "failed", "deleted"]
    - attachment_ids [list of strings, default None]: list of IndividualAccountAttachment ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
    - user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call.
    ## Return:
    - generator of individualaccountattachment.Log objects with updated attributes
    """
    return rest.get_stream(
        resource=_resource,
        limit=limit,
        after=check_date(after),
        before=check_date(before),
        types=types,
        attachment_ids=attachment_ids,
        user=user,
    )


def page(cursor=None, limit=None, after=None, before=None, types=None, attachment_ids=None, user=None):
    """# Retrieve paged individualaccountattachment.Logs
    Receive a list of up to 100 individualaccountattachment.Log objects previously created in the Stark Infra API and the cursor to the next page.
    Use this function instead of query if you want to manually page your requests.
    ## Parameters (optional):
    - cursor [string, default None]: cursor returned on the previous page function call
    - limit [integer, default 100]: maximum number of objects to be retrieved. It must be an integer between 1 and 100. ex: 50
    - after [datetime.date or string, default None]: date filter for objects created only after specified date. ex: datetime.date(2020, 3, 10)
    - before [datetime.date or string, default None]: date filter for objects created only before specified date. ex: datetime.date(2020, 3, 10)
    - types [list of strings, default None]: filter for log event types. ex: ["created", "success", "failed", "deleted"]
    - attachment_ids [list of strings, default None]: list of IndividualAccountAttachment ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
    - user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call.
    ## Return:
    - list of individualaccountattachment.Log objects with updated attributes
    - cursor to retrieve the next page of individualaccountattachment.Log objects
    """
    return rest.get_page(
        resource=_resource,
        cursor=cursor,
        limit=limit,
        after=check_date(after),
        before=check_date(before),
        types=types,
        attachment_ids=attachment_ids,
        user=user,
    )
