from ...utils import rest
from starkcore.utils.resource import Resource
from starkcore.utils.api import from_api_json
from starkcore.utils.checks import check_datetime, check_date
from ..__pixkeyholmes import _resource as _pixkeyholmes_resource


class Log(Resource):
    """# PixKeyHolmes.Log object
    Every time a PixKeyHolmes entity is updated, a corresponding PixKeyHolmes.Log
    is generated for the entity. This log is never generated by the
    user, but it can be retrieved to check additional information
    on the PixKeyHolmes.
    ## Attributes (return-only):
    - id [string]: unique id returned when the log is created. ex: "5656565656565656"
    - holmes [PixKeyHolmes]: PixKeyHolmes entity to which the log refers to.
    - type [string]: type of the PixKeyHolmes event which triggered the log creation. ex: "solving", "solved"
    - errors [list of strings]: list of errors linked to this PixKeyHolmes event
    - created [datetime.datetime]: creation datetime for the log. ex: datetime.datetime(2020, 3, 10, 10, 30, 0, 0)
    """

    def __init__(self, id, holmes, type, errors, created):
        Resource.__init__(self, id=id)

        self.holmes = from_api_json(_pixkeyholmes_resource, holmes)
        self.type = type
        self.errors = errors
        self.created = check_datetime(created)


_resource = {"class": Log, "name": "PixKeyHolmesLog"}


def get(id, user=None):
    """# Retrieve a specific PixKeyHolmes.Log
    Receive a single PixKeyHolmes.Log object previously created by the Stark Infra API by its id
    ## Parameters (required):
    - id [string]: object unique id. ex: "5656565656565656"
    ## Parameters (optional):
    - user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call.
    ## Return:
    - PixKeyHolmes.Log object with updated attributes
    """
    return rest.get_id(resource=_resource, id=id, user=user)


def query(ids=None, limit=None, after=None, before=None, types=None, holmes_ids=None, user=None):
    """# Retrieve PixKeyHolmes.Logs
    Receive a generator of PixKeyHolmes.Log objects previously created in the Stark Infra API
    ## Parameters (optional):
    - ids [list of strings, default None]: Log ids to filter PixKeyHolmes Logs. ex: ["5656565656565656"]
    - limit [integer, default None]: maximum number of objects to be retrieved. Unlimited if None. ex: 35
    - after [datetime.date or string, default None]: date filter for objects created only after specified date. ex: datetime.date(2020, 3, 10)
    - before [datetime.date or string, default None]: date filter for objects created only before specified date. ex: datetime.date(2020, 3, 10)
    - types [list of strings, default None]: filter for log event types. ex: ["solving", "solved"]
    - holmes_ids [list of strings, default None]: list of PixKeyHolmes ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
    - user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call.
    ## Return:
    - generator of PixKeyHolmes.Log objects with updated attributes
    """
    return rest.get_stream(
        resource=_resource,
        ids=ids,
        limit=limit,
        after=check_date(after),
        before=check_date(before),
        types=types,
        holmes_ids=holmes_ids,
        user=user,
    )


def page(cursor=None, ids=None, limit=None, after=None, before=None, types=None, holmes_ids=None, user=None):
    """# Retrieve paged PixKeyHolmes.Logs
    Receive a list of up to 100 PixKeyHolmes.Log objects previously created in the Stark Infra API and the cursor to the next page.
    Use this function instead of query if you want to manually page your requests.
    ## Parameters (optional):
    - cursor [string, default None]: cursor returned on the previous page function call
    - ids [list of strings, default None]: Log ids to filter PixKeyHolmes Logs. ex: ["5656565656565656"]
    - limit [integer, default 100]: maximum number of objects to be retrieved. It must be an integer between 1 and 100. ex: 50
    - after [datetime.date or string, default None]: date filter for objects created only after specified date. ex: datetime.date(2020, 3, 10)
    - before [datetime.date or string, default None]: date filter for objects created only before specified date. ex: datetime.date(2020, 3, 10)
    - types [list of strings, default None]: filter for log event types. ex: ["solving", "solved"]
    - holmes_ids [list of strings, default None]: list of PixKeyHolmes ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
    - user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call.
    ## Return:
    - list of PixKeyHolmes.Log objects with updated attributes
    - cursor to retrieve the next page of PixKeyHolmes.Log objects
    """
    return rest.get_page(
        resource=_resource,
        cursor=cursor,
        ids=ids,
        limit=limit,
        after=check_date(after),
        before=check_date(before),
        types=types,
        holmes_ids=holmes_ids,
        user=user,
    )
