from ...utils import rest
from starkcore.utils.resource import Resource
from starkcore.utils.api import from_api_json
from starkcore.utils.checks import check_datetime, check_date
from ..__pixpullrequest import _resource as _pixpullrequest_resource


class Log(Resource):
    """# PixPullRequest.Log object
    Every time a PixPullRequest entity is modified, a corresponding PixPullRequest.Log
    is generated for the entity. This log is never generated by the user.
    ## Attributes (return-only):
    - id [string]: unique id returned when the log is created. ex: "5656565656565656"
    - request [PixPullRequest]: PixPullRequest entity to which the log refers to.
    - type [string]: type of the PixPullRequest event which triggered the log creation. Options: "created", "sent", "scheduled", "denied", "success", "canceling", "canceled", "expired"
    - errors [list of dictionaries]: list of errors linked to this PixPullRequest event. ex: [{"code": "invalidStatus", "message": "Cannot change status from canceled to scheduled"}]
    - created [datetime.datetime]: creation datetime for the log.
    """
    def __init__(self, id, request, type, errors, created):
        Resource.__init__(self, id=id)

        self.request = from_api_json(_pixpullrequest_resource, request)
        self.type = type
        self.errors = errors
        self.created = check_datetime(created)


_resource = {"class": Log, "name": "PixPullRequestLog"}


def get(id, user=None):
    """# Retrieve a specific PixPullRequest.Log
    Receive a single PixPullRequest.Log object previously created by the Stark Infra API by its id
    ## Parameters (required):
    - id [string]: object unique id. ex: "5656565656565656"
    ## Parameters (optional):
    - user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call.
    ## Return:
    - PixPullRequest.Log object with updated attributes
    """
    return rest.get_id(resource=_resource, id=id, user=user)


def query(ids=None, limit=None, after=None, before=None, types=None, request_ids=None, user=None):
    """# Retrieve PixPullRequest.Logs
    Receive a generator of PixPullRequest.Log objects previously created in the Stark Infra API
    ## Parameters (optional):
    - ids [list of strings, default None]: list of ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
    - limit [integer, default None]: maximum number of objects to be retrieved. Unlimited if None. ex: 35
    - after [datetime.date or string, default None]: date filter for objects created after a specified date. ex: datetime.date(2020, 3, 10)
    - before [datetime.date or string, default None]: date filter for objects created before a specified date. ex: datetime.date(2020, 3, 10)
    - types [list of strings, default None]: filter for log event types. Options: "created", "sent", "scheduled", "denied", "success", "canceling", "canceled", "expired"
    - request_ids [list of strings, default None]: list of PixPullRequest ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
    - user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call.
    ## Return:
    - generator of PixPullRequest.Log objects with updated attributes
    """
    return rest.get_stream(
        resource=_resource,
        ids=ids,
        limit=limit,
        after=check_date(after),
        before=check_date(before),
        types=types,
        request_ids=request_ids,
        user=user,
    )


def page(cursor=None, ids=None, limit=None, after=None, before=None, types=None, request_ids=None, user=None):
    """# Retrieve paged PixPullRequest.Logs
    Receive a list of up to 100 PixPullRequest.Log objects previously created in the Stark Infra API and the cursor to the next page.
    ## Parameters (optional):
    - cursor [string, default None]: cursor returned on the previous page function call.
    - ids [list of strings, default None]: list of ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
    - limit [integer, default 100]: maximum number of objects to be retrieved. Max = 100. ex: 50
    - after [datetime.date or string, default None]: date filter for objects created after a specified date. ex: datetime.date(2020, 3, 10)
    - before [datetime.date or string, default None]: date filter for objects created before a specified date. ex: datetime.date(2020, 3, 10)
    - types [list of strings, default None]: filter for log event types. Options: "created", "sent", "scheduled", "denied", "success", "canceling", "canceled", "expired"
    - request_ids [list of strings, default None]: list of PixPullRequest ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
    - user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call.
    ## Return:
    - list of PixPullRequest.Log objects with updated attributes
    - cursor for the next page
    """
    return rest.get_page(
        resource=_resource,
        cursor=cursor,
        ids=ids,
        limit=limit,
        after=check_date(after),
        before=check_date(before),
        types=types,
        request_ids=request_ids,
        user=user,
    )
